name: wireguard_linux
description: For interfacing with wireguard in linux.
version: 0.0.1
repository: https://github.com/j4qfrost/wireguard-linux-dart.git

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  cli_config: ^0.1.1
  ffi: ^2.1.0
  logging: ^1.2.0
  native_assets_cli: ^0.2.0
  native_toolchain_c: ^0.2.0

dev_dependencies:
  ffigen: ^9.0.1
  http: ^1.1.0
  lints: ^2.0.0
  test: ^1.21.0
